version: '3'

volumes:
  db:
    driver: local

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - db
    environment:
      smite.datasource.jdbcUrl: jdbc:mysql://db:3307/smite_api
      session.datasource.jdbcUrl: jdbc:mysql://db:3307/smite_session
  db:
    image: mysql/mysql-server:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: Brave99_
      MYSQL_USER: jask24
      MYSQL_PASSWORD: Brave99_